name: PR open test build images
on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build_docker_image:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ vars.DOCKER_HUB_USERNAME }}/gatewise
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}

    - name: setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64, linux/amd64

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/arm64, linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: echo tag build
      run: |
        echo '${{ steps.meta.outputs.tags }}[0]'

    - name: upload gatewise deploy version
      uses: actions/upload-artifact@v3
      with:
        name: gatewise-version
        path: /tmp/version

  update_new_build_version:
    needs: [build_docker_image]
    runs-on: ubuntu-22.04
    steps:
    - name: get gatewise build version
      uses: actions/download-artifact@v3
      with:
        name: gatewise-version
        path: ./

    - name: Checkout manifests repo
      uses: actions/checkout@v3
      with:
        repository: lhtran-organization/gatewise-manifests
        ssh-key: ${{ secrets.GATEWISE_MANIFESTS_DEPLOY_PRIVATE_KEY }} 

