name: PR open test build images
on:
  push:
    branches: [ master ]
    tags:
    - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build_docker_image:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ vars.DOCKER_HUB_USERNAME }}/gatewise
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}

    - name: setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64, linux/amd64

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/arm64, linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: save image name
      run: |
        echo '${{ steps.meta.outputs.tags }}' | head -1 > /tmp/${{ vars.GATEWISE_IMAGE_TXT }}

    - name: upload gatewise image name
      uses: actions/upload-artifact@v3
      with:
        name: ${{ vars.GATEWISE_IMAGE_TXT }}
        path: /tmp/${{ vars.GATEWISE_IMAGE_TXT }}

  update_manifests_repo:
    if: ${{ github.event_name == 'push' }} && ${{ github.ref == 'refs/heads/master' }}
    needs: [build_docker_image]
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout manifests repo
      uses: actions/checkout@v3
      with:
        repository: lhtran-organization/helper-scripts
        ssh-key: ${{ secrets.HELPER_SCRIPTS_PRIVATE_KEY }}
        path: ./helper-scripts

    - name: Checkout manifests repo
      uses: actions/checkout@v3
      with:
        repository: lhtran-organization/gatewise-manifests
        ssh-key: ${{ secrets.GATEWISE_MANIFESTS_DEPLOY_PRIVATE_KEY }}
        path: ./manifest

    - name: download gatewise image name
      uses: actions/download-artifact@v3
      with:
        name: ${{ vars.GATEWISE_IMAGE_TXT }}
        path: ./

    - working-directory: ./manifest
      run: |
        pwd
        ls -l
        pip install ruamel.yaml
        python ../helper-scripts/kubernetes/deploy_image_update.py ./deployment.yaml longhtran91/gatewise $(cat ../${{ vars.GATEWISE_IMAGE_TXT }})
        git config user.email "gatewiserepo@lhtran.com"
        git config user.name "Gatewise Repo"
        git add deployment.yaml
        git commit -m "update deployment image"
        git push

