name: Build gatewise and push to DockerHub
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_docker_image:
    runs-on: ubuntu-22.04
    environment: production
    steps:
    - run: echo 'username ${{ env.TEST }}'
    - name: Checkout
      uses: actions/checkout@v3

    - name: setup QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64, linux/amd64

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/arm64, linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gatewise:latest
